// VRF Adapter — Switchboard On-Demand VRF integration framework.
//
// This module provides the on-chain interface for provably fair reveals
// using Switchboard's VRF. It replaces the commit-reveal pattern with
// cryptographic randomness that the creator cannot influence.
//
// Integration plan:
// 1. Collection creator requests VRF randomness from a Switchboard VRF account
// 2. The VRF result (32 bytes) is submitted on-chain via `reveal_with_vrf`
// 3. The program verifies the result came from the configured Switchboard account
// 4. Reveal entropy = VRF result (no secret needed, no commit step)
//
// To activate:
// - Add `switchboard-on-demand = "1.0"` to Cargo.toml [dependencies]
// - Add `vrf` module to lib.rs
// - Add `reveal_with_vrf` instruction that calls `verify_vrf_result`
// - Add `vrf_account: Pubkey` to CollectionConfig (Switchboard VRF account)
//
// Current status: Framework only — not wired into an active instruction.
// Commit-reveal remains the active randomness mechanism.

use anchor_lang::prelude::*;

/// Verify a Switchboard VRF result on-chain.
///
/// In production, this would CPI into the Switchboard program to verify
/// that the provided randomness was generated by the configured VRF account.
///
/// For now, this is a placeholder that documents the expected interface.
/// When `switchboard-on-demand` is added as a dependency, replace the
/// body with the actual verification CPI call.
pub fn verify_vrf_result(
    _vrf_account: &Pubkey,
    _vrf_result: &[u8; 32],
) -> Result<bool> {
    // TODO: Replace with Switchboard VRF verification:
    //
    // let vrf = VrfAccount::load(vrf_account_info)?;
    // let result = vrf.get_result()?;
    // require!(result == vrf_result, EvoError::VrfMismatch);
    // Ok(true)
    //
    // For now, return false to indicate VRF is not yet active.
    Ok(false)
}

/// Derive reveal entropy from a VRF result.
/// This replaces `keccak256(secret)` in the commit-reveal flow.
pub fn vrf_to_entropy(vrf_result: &[u8; 32]) -> [u8; 32] {
    // The VRF result itself is already random — use it directly.
    // Additional hashing is optional but doesn't hurt.
    *vrf_result
}